/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { BankAccountFindManyArgs } from "../../bankAccount/base/BankAccountFindManyArgs";
import { BankAccount } from "../../bankAccount/base/BankAccount";
import { BankAccountWhereUniqueInput } from "../../bankAccount/base/BankAccountWhereUniqueInput";
import { CreditCardFindManyArgs } from "../../creditCard/base/CreditCardFindManyArgs";
import { CreditCard } from "../../creditCard/base/CreditCard";
import { CreditCardWhereUniqueInput } from "../../creditCard/base/CreditCardWhereUniqueInput";
import { LoanFindManyArgs } from "../../loan/base/LoanFindManyArgs";
import { Loan } from "../../loan/base/Loan";
import { LoanWhereUniqueInput } from "../../loan/base/LoanWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bankAccounts")
  @ApiNestedQuery(BankAccountFindManyArgs)
  async findBankAccounts(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<BankAccount[]> {
    const query = plainToClass(BankAccountFindManyArgs, request.query);
    const results = await this.service.findBankAccounts(params.id, {
      ...query,
      select: {
        accountNumber: true,
        accountType: true,
        balance: true,
        bankName: true,
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bankAccounts")
  async connectBankAccounts(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: BankAccountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bankAccounts: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bankAccounts")
  async updateBankAccounts(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: BankAccountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bankAccounts: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bankAccounts")
  async disconnectBankAccounts(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: BankAccountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bankAccounts: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/creditCards")
  @ApiNestedQuery(CreditCardFindManyArgs)
  async findCreditCards(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<CreditCard[]> {
    const query = plainToClass(CreditCardFindManyArgs, request.query);
    const results = await this.service.findCreditCards(params.id, {
      ...query,
      select: {
        cardNumber: true,
        cardType: true,
        createdAt: true,
        creditLimit: true,
        expirationDate: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/creditCards")
  async connectCreditCards(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CreditCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      creditCards: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/creditCards")
  async updateCreditCards(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CreditCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      creditCards: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/creditCards")
  async disconnectCreditCards(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: CreditCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      creditCards: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/loans")
  @ApiNestedQuery(LoanFindManyArgs)
  async findLoans(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Loan[]> {
    const query = plainToClass(LoanFindManyArgs, request.query);
    const results = await this.service.findLoans(params.id, {
      ...query,
      select: {
        createdAt: true,
        endDate: true,
        id: true,
        interestRate: true,
        loanAmount: true,
        startDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/loans")
  async connectLoans(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: LoanWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      loans: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/loans")
  async updateLoans(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: LoanWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      loans: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/loans")
  async disconnectLoans(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: LoanWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      loans: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
