/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BankAccountUpdateManyWithoutUsersInput } from "./BankAccountUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CreditCardUpdateManyWithoutUsersInput } from "./CreditCardUpdateManyWithoutUsersInput";
import { LoanUpdateManyWithoutUsersInput } from "./LoanUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BankAccountUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => BankAccountUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => BankAccountUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  bankAccounts?: BankAccountUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CreditCardUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CreditCardUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CreditCardUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  creditCards?: CreditCardUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LoanUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LoanUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LoanUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  loans?: LoanUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
