/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BankAccountService } from "../bankAccount.service";
import { BankAccountCreateInput } from "./BankAccountCreateInput";
import { BankAccount } from "./BankAccount";
import { BankAccountFindManyArgs } from "./BankAccountFindManyArgs";
import { BankAccountWhereUniqueInput } from "./BankAccountWhereUniqueInput";
import { BankAccountUpdateInput } from "./BankAccountUpdateInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";

export class BankAccountControllerBase {
  constructor(protected readonly service: BankAccountService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BankAccount })
  async createBankAccount(
    @common.Body() data: BankAccountCreateInput
  ): Promise<BankAccount> {
    return await this.service.createBankAccount({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        accountNumber: true,
        accountType: true,
        balance: true,
        bankName: true,
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [BankAccount] })
  @ApiNestedQuery(BankAccountFindManyArgs)
  async bankAccounts(@common.Req() request: Request): Promise<BankAccount[]> {
    const args = plainToClass(BankAccountFindManyArgs, request.query);
    return this.service.bankAccounts({
      ...args,
      select: {
        accountNumber: true,
        accountType: true,
        balance: true,
        bankName: true,
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BankAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async bankAccount(
    @common.Param() params: BankAccountWhereUniqueInput
  ): Promise<BankAccount | null> {
    const result = await this.service.bankAccount({
      where: params,
      select: {
        accountNumber: true,
        accountType: true,
        balance: true,
        bankName: true,
        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BankAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBankAccount(
    @common.Param() params: BankAccountWhereUniqueInput,
    @common.Body() data: BankAccountUpdateInput
  ): Promise<BankAccount | null> {
    try {
      return await this.service.updateBankAccount({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          accountNumber: true,
          accountType: true,
          balance: true,
          bankName: true,
          createdAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BankAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBankAccount(
    @common.Param() params: BankAccountWhereUniqueInput
  ): Promise<BankAccount | null> {
    try {
      return await this.service.deleteBankAccount({
        where: params,
        select: {
          accountNumber: true,
          accountType: true,
          balance: true,
          bankName: true,
          createdAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: BankAccountWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        amount: true,

        bankAccount: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  async connectTransactions(
    @common.Param() params: BankAccountWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updateBankAccount({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  async updateTransactions(
    @common.Param() params: BankAccountWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updateBankAccount({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  async disconnectTransactions(
    @common.Param() params: BankAccountWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updateBankAccount({
      where: params,
      data,
      select: { id: true },
    });
  }
}
